version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-raffle
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: raffle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
  
  mongo:
    image: mongo:latest
    container_name: mongo-raffle
    ports:
      - "27018:27017"
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express-raffle
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27018/
      ME_CONFIG_BASICAUTH: false

networks:
  mongo-compose-network:
    driver: bridge